//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanabel.Presentation.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanabel.Presentation.Localization.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة الهاتف.
        /// </summary>
        public static string AddPhoneSuccess {
            get {
                return ResourceManager.GetString("AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح..
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكر لك لتأكيد البريد الالكتروني. برجاء &lt;a href=&quot;{0}&quot;&gt;الضغط هنا لتسجيل الدخول&lt;/a&gt;.
        /// </summary>
        public static string EmailConfimrationSucessMessage {
            get {
                return ResourceManager.GetString("EmailConfimrationSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد البريد الإلكتروني.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء تأكيد البريد الإلكتروني الخاص بك بالضغط &lt;a href=&quot;{0}&quot;&gt;هنا&lt;/a&gt;.
        /// </summary>
        public static string EmailConfirmationMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء مراجعة البريد الإلكتروني الخاص بك.لتأكيد البريد الإلكتروني لتستطيع تسجيل الدخول..
        /// </summary>
        public static string EmailIsNotConfirmedMessage {
            get {
                return ResourceManager.GetString("EmailIsNotConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد تغيير كلمة المرور.
        /// </summary>
        public static string ForgetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء مراجعة البريد الإلكتروني الخاص به لتغيير كلمة المرور..
        /// </summary>
        public static string ForgetPasswordConfirmationMessage {
            get {
                return ResourceManager.GetString("ForgetPasswordConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور ؟.
        /// </summary>
        public static string ForgetPasswordLinkText {
            get {
                return ResourceManager.GetString("ForgetPasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعادة كلمة المرور.
        /// </summary>
        public static string ForgetPasswordPageTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال البريد الإلكتروني الخاص بك.
        /// </summary>
        public static string ForgetPasswordTip {
            get {
                return ResourceManager.GetString("ForgetPasswordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الحساب غير صحيحة.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكنكم تسجيل الدخول هنا.
        /// </summary>
        public static string LoginTip {
            get {
                return ResourceManager.GetString("LoginTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما.
        /// </summary>
        public static string ManagerError {
            get {
                return ResourceManager.GetString("ManagerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعية سنابل.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الهاتف.
        /// </summary>
        public static string RemovePhoneSuccess {
            get {
                return ResourceManager.GetString("RemovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور الخاصة بك..
        /// </summary>
        public static string ResetPasswordConfimationMessage {
            get {
                return ResourceManager.GetString("ResetPasswordConfimationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد تغيير كلمة المرور.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء الضغط هنا لتسجيل الدخول.
        /// </summary>
        public static string ResetPasswordConfirmationLoginLinkText {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationLoginLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجاء الضغط علي الرابط لتغيير كلمة المرور &lt;a href=&quot;{0}&quot;&gt;هنا&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordEmail {
            get {
                return ResourceManager.GetString("ResetPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور.
        /// </summary>
        public static string SetPasswordSuccess {
            get {
                return ResourceManager.GetString("SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعيين التحقق .
        /// </summary>
        public static string SetTwoFactorSuccess {
            get {
                return ResourceManager.GetString("SetTwoFactorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
    }
}
