// <auto-generated />
namespace Sanable.Cases.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPlaceToCases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPlaceToCases));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191346460_AddPlaceToCases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
