// <auto-generated />
namespace Sanable.Cases.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addcasecolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcasecolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201805161631151_addcasecolumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
