//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonSettings.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonSettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonSettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonSettings.Localization.CommonSettingsResources", typeof(CommonSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود المدينة.
        /// </summary>
        public static string CityCode {
            get {
                return ResourceManager.GetString("CityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة انجليزي.
        /// </summary>
        public static string CityNameEn {
            get {
                return ResourceManager.GetString("CityNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الدولة.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الدولة أو أسم الدولة مكرر.
        /// </summary>
        public static string CountryDuplicatedMessage {
            get {
                return ResourceManager.GetString("CountryDuplicatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسم الدولة.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الدولة بالإنجليزية.
        /// </summary>
        public static string CountryNameEn {
            get {
                return ResourceManager.GetString("CountryNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحي.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الحي.
        /// </summary>
        public static string DistrictCode {
            get {
                return ResourceManager.GetString("DistrictCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحي.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحي انجليزي.
        /// </summary>
        public static string DistrictNameEn {
            get {
                return ResourceManager.GetString("DistrictNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود المنطقة.
        /// </summary>
        public static string RegionCode {
            get {
                return ResourceManager.GetString("RegionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنطقة.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنطقة الانجليزي.
        /// </summary>
        public static string RegionNameEn {
            get {
                return ResourceManager.GetString("RegionNameEn", resourceCulture);
            }
        }
    }
}
